name: Build Tauri App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: 安装 Linux 构建依赖（仅限 Linux）
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: 安装依赖
        run: npm install

      - name: 构建前端
        run: npm run build

      - name: 安装 Tauri CLI
        run: npm install tauri

      - name: 构建 Tauri 应用
        run: npx tauri build

      - name: 搜集构建产物路径
        id: get-artifacts
        run: |
          set -e
          mkdir -p artifacts

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp src-tauri/target/release/bundle/msi/*.msi artifacts/installer-windows.msi
            cp src-tauri/target/release/*.exe artifacts/portable-windows.exe
          else
            cp src-tauri/target/release/bundle/deb/*.deb artifacts/installer-linux.deb
            cp src-tauri/target/release/bundle/appimage/*.AppImage artifacts/portable-linux.AppImage
          fi

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: tauri-artifacts-${{ matrix.os }}
          path: artifacts/

      - name: 发布 GitHub Release（每个平台）
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v1.0.5-1"
          name: "BlueArchiveGM Release v1.0.5-1 多平台"
          body: |
            本次发布修复了以下内容：

            - 🛠️ 修复设置学生属性时报“无 Key”问题。
            - 💻 构建支持：Windows（安装版 + 绿色版），Linux（.deb 安装包 + .AppImage）。

            感谢使用！
          draft: false
          prerelease: false
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.KITANO_GM_TOKEN }}
